name: Github Pages Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: gh-pages
    strategy:
      matrix:
        node-version: [16.16.0]
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      REACT_APP_APIKEY: ${{secrets.REACT_APP_APIKEY}}
      REACT_APP_AUTH_DOMAIN: ${{secrets.REACT_APP_AUTH_DOMAIN}}
      REACT_APP_PROJECT_ID: ${{secrets.REACT_APP_PROJECT_ID}}
      REACT_APP_STORAGE_BUCKET: ${{secrets.REACT_APP_STORAGE_BUCKET}}
      REACT_APP_MESSAGING_SENDER_ID: ${{secrets.REACT_APP_MESSAGING_SENDER_ID}}
      REACT_APP_APP_ID: ${{secrets.REACT_APP_APP_ID}}
      REACT_APP_MEASUREMENT_ID: ${{secrets.REACT_APP_MEASUREMENT_ID}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean
        run: rm -rf node_modules/.cache/gh-pages
      - name: Install
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
  createtag:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Get package.json version"
        id: set_var
        run: |
          echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV
      - name: "Show version"
        run: |
          echo "${{fromJson(env.PACKAGE_JSON).version}}"
      - name: "Create tag"
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{fromJson(env.PACKAGE_JSON).version}}
          tag_exists_error: false
          force_push_tag: true
          message: "Latest release: ${{ github.event.head_commit.message }}"
