name: Github Pages Deploy

on:
  push:
    tags:
      - "V1.*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: gh-pages
    strategy:
      matrix:
        node-version: [15.x]
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      REACT_APP_APIKEY: ${{secrets.REACT_APP_APIKEY}}
      REACT_APP_AUTH_DOMAIN: ${{secrets.REACT_APP_AUTH_DOMAIN}}
      REACT_APP_PROJECT_ID: ${{secrets.REACT_APP_PROJECT_ID}}
      REACT_APP_STORAGE_BUCKET: ${{secrets.REACT_APP_STORAGE_BUCKET}}
      REACT_APP_MESSAGING_SENDER_ID: ${{secrets.REACT_APP_MESSAGING_SENDER_ID}}
      REACT_APP_APP_ID: ${{secrets.REACT_APP_APP_ID}}
      REACT_APP_MEASUREMENT_ID: ${{secrets.REACT_APP_MEASUREMENT_ID}}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Clean
        run: rm -rf node_modules/.cache/gh-pages
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
